### ISSUE TITLE
Module version mismatch. Expected 47, got 46.

### ISSUE THREAD

**Issue by Saarg** [jduncanator/node-diskusage#11]
hi, i'm trying to use your module but i got this error:
`Error: Module version mismatch. Expected 47, got 46.`

any idea why?

**Comment by jduncanator** [comment]
There seems to be a few issues cropping up with newer versions of node, and node-gyp. I'll have some free time this weekend to sort them out.

**Comment by Camyll** [comment]
I keep getting this error: 

Error: Module version mismatch. Expected 50, got 49.

has the previous issue ever been resolved?

**Comment by jduncanator** [comment]
@Camyll Yea, in the past people have fixed the issue by rebuilding their node-gyp modules. `node-gyp rebuild` should do the trick.

**Comment by Camyll** [comment]
This is not working for me :(

**Comment by jduncanator** [comment]
@Camyll Could you try the instructions listed [here](https://github.com/electron-userland/electron-builder/issues/453#issuecomment-222734707)

**Comment by ak2766** [comment]
I too am getting this issue on my daily driver laptop.  However, on one of my LXC containers, it is working well.  So I first compared versions:

LXC container (*working*):

    $ npm -v
    3.10.3

Laptop (*errors out*):

    $ npm -v
    3.10.9

I then compared the node_modules directory on both systems.  All `package.json` files on the working LXC container have a line that says `"_installable": true,` while that line is missing on all `package.json` files on laptop.

Any ideas why?  Obviously I think that downgrading `npm` will work, but why was that line removed?

**Comment by jduncanator** [comment]
@ak2766 The issue stems from an issue with node-gyp trying to compile node-ffi and dependencies. By copying over your node_modules, you are essentially skipping the compilation step on your laptop and using the pre-built binaries generated in your container.

I've been doing some investigations over the last few weeks to try and get to the bottom of it, but it seems to be an issue within the node source tree, something not easy to fix. I'm in discussions with some people in the know on how we can address the issue.

**Comment by jduncanator** [comment]
It seems that this is caused by updating your Node version without rebuilding your Node modules. This makes sense as node-gyp compiles native modules against the currently installed version of node. Try following some of the steps [here](http://stackoverflow.com/questions/15584529/module-version-mismatch-expected-11-got-1) to see if it fixes your problem.

**Comment by jduncanator** [comment]
As of version 0.2.0 diskusage now uses native, platform specific bindings. This should resolve any of the previous installation issues. If you are still experiencing issues, feel free to comment on this issue and I will take a further look.
