### ISSUE TITLE
Cannot install on OS X

### ISSUE THREAD

**Issue by ugieska** [jduncanator/node-diskusage#12]
I tried to install this module, and it fails. I'm using the n module to change node versions, but whether on Node 4, 5, or 6, installation fails every time.

I do make sure that I clean out the `node_modules` folder and re-install everything via `npm install` after switching versions. It still doesn't work.

I've attached the `npm-debug.log` file, with a `.txt` extension added (so GitHub will allow it), and with my user name and app name replaced. But, the tl;dr version is that `node-gyp rebuild` is failing.
[npm-debug.log.txt](https://github.com/jduncanator/node-diskusage/files/548319/npm-debug.log.txt)

**Comment by jduncanator** [comment]
It looks like it's failing at installing [ref](https://github.com/TooTallNate/ref). The dependencies are in dire need of updating so I will push a new version with updated dependencies. I'm just not sure, due to the rather fragile nature of native bindings, how well newer versions of ffi and ref work with older versions of node.

**Comment by jduncanator** [comment]
See https://github.com/jduncanator/node-diskusage/issues/11#issuecomment-257183794

**Comment by ugieska** [comment]
I'm not sure why this was closed. Is it a duplicate of #11 ? I did totally delete node_modules every time I switched versions, and it still wouldn't install. Did you mean some other process in the comment?

**Comment by jduncanator** [comment]
@ugieska Did you try the instructions linked to in #11? If so, and it did not work for you, I'll re-open.

**Comment by jduncanator** [comment]
@ugieska  [This thread](https://github.com/nodejs/node-gyp/issues/809) suggests that it could be caused by a space in your home path. Do you have a space in your username or your $HOME path?

**Comment by ugieska** [comment]
Sorry, I only just saw these questions... Here is what I am doing, specifically:

* I should have mentioned that I am installing this to the project, not globally: `npm install --save diskusage`. This puts the module into the `package.json` file as a dependency.

* After switching Node versions using n, I delete *everything* in the project's `node_modules` and re-install using the `package.json` in the project: `rm -rf node_modules/; npm install`

    As far as I can tell from the links in #11 and the linked thread, this is the proposed solution, and it is not working.

* FWIW, I do not have any spaces in my $HOME env var. Also, there are no spaces in the path to the project's `node_modules` directory. But since this module would need to be deployed in multiple server instances/environments on AWS, I can't make the guarantee that this will always be the case.

For the moment, my company has decided it doesn't need this module. But I'll keep monitoring this issue.

**Comment by jduncanator** [comment]
Are you sure you have the correct build dependencies installed? I'm not sure what is required on MacOS, but on Windows it is Visual Studio and Linux it is GCC. Make sure you have XCode installed.

**Comment by jduncanator** [comment]
As of version 0.2.0 diskusage now uses native, platform specific bindings. This should resolve any of the previous installation issues. If you are still experiencing issues, feel free to comment on this issue and I will take a further look.
