### ISSUE TITLE
Feature request: return errno on error

### ISSUE THREAD

**Issue by frontierpsycho** [jduncanator/node-diskusage#13]
According to the [statvfs man page](https://linux.die.net/man/2/statvfs), statvfs sets `errno` on error. It would be great if diskusage could capture that and make it available to the callback.

Any plans to support that? Not sure how to do it, otherwise I'd do it myself.

**Comment by jduncanator** [comment]
The return code is already passed back in an error scenario as the first parameter of the callback. Relevant code is [here](https://github.com/jduncanator/node-diskusage/blob/300308f4a966f67fc61a1638a76ea30a9a676a11/index.js#L64-L66).

An example:

```
var disk = require('diskusage');

// get disk usage. Takes mount point as first parameter
disk.check('/', function(retcode, info) {
    if(retcode !== undefined) {
        console.log('statvfs return code was %i', retcode);
    } else {
        console.log(info.available);
        console.log(info.free);
        console.log(info.total);
    }
});
```

**Comment by jduncanator** [comment]
Sorry, just noticed you were referring to `errno` not the return code. I'll make some changes to return the `errno` instead of `-1` on Linux and Darwin.

**Comment by frontierpsycho** [comment]
Great, thanks!

Perhaps a good idea would be to return a `SystemError` (see [here](https://nodejs.org/api/errors.html#errors_system_errors)), which has fields for `code` and `errno`. Furthermore, if you have the patience for it, 

The _best_ thing would be if you even used [explain_statvfs](https://linux.die.net/man/3/explain_statvfs) to actually return a detailed message explaining what the cause of the error was. From the `explain_statvfs` man page:

> The explain_statvfs function is used to obtain an explanation of an error returned by the statvfs(2) system call. The least the message will contain is the value of strerror(errno), but usually it will do much better, and indicate the underlying cause in more detail.
> 
> The errno global variable will be used to obtain the error value to be decoded.

Even if you just return the error code, that would be great, though. I'm just saying.

Cheers!

**Comment by jduncanator** [comment]
My only concern with `explain_statvfs` is the fact it is not thread-safe. Node.js uses it extensively internally, and as the output buffer is shared between calls to `explain_statvfs`, any other call to it internally will return an incorrect message (or do potentially worst things). I'll need to take a look at a thread-safe way of calling `explain_statvfs` so it does not conflict with Node's own calls.

**Comment by frontierpsycho** [comment]
:+1:

**Comment by jduncanator** [comment]
@frontierpsycho It doesn't appear that `SystemError` has an appropriate field to store the explanation message in. In your opinion, where would you store the explained errno message?

**Comment by frontierpsycho** [comment]
Judging by this sentence in the docs:

> In Node.js, system errors are represented as augmented Error objects with added properties.

and also by looking around the node source code, I think system errors are nothing but simple `Error` objects with the extra fields `.syscall`, `.errno` and `.code`, so they should have all the fields of `Error`, including `.message`. I think you can probably store it there.

Does that make sense?

**Comment by jduncanator** [comment]
With v0.2.0 you should now have a bit more visibility into the error messages being thrown. It doesn't yet use `explain_statvfs` because I'm trying to keep the behavior consistent across platforms. I'll take a look at finding a Windows solution later this week.

**Comment by frontierpsycho** [comment]
Great, thanks! I'll look into it soon.

**Comment by jduncanator** [comment]
I ended up removing the dependency on libexplain (`explain_statvfs`) because it was a hassle to get the dependency installed for users (I thought it came out of the box on most installations, but that assumption was incorrect). I've since just settled for `strerror` on POSIX platforms. It gives a detailed enough error message.
