### ISSUE TITLE
Re-implement in C++ with just NaN dependency

### ISSUE THREAD

**Issue by miniak** [jduncanator/node-diskusage#14]
I think that this module should be implemented in C++ using the NaN module to ensure compatibility with different NodeJS versions. It would decrease the number all dependencies from 8 to 1.

**Comment by jduncanator** [comment]
Thanks! I've been meaning to get around to this, but as it worked (for the most part) as it was, it wasn't a high priority.

**Comment by miniak** [comment]
There is one small thing remaining and that's the error argument of the callback. I think that it actually wasn't returning a correct value before (not zero on failure) on Windows.

**Comment by jduncanator** [comment]
Your right, it was returning 0 for the error argument. That's been another thing I've been wanting to change, returning proper error responses. There was a suggestion on #13 to return the errno on Posix based systems, something similar might be doable on Windows systems as well. Will take a look.

**Comment by jduncanator** [comment]
Merged! Thank you for the pull request.
