### ISSUE TITLE
Fail to pass Travis CI 

### ISSUE THREAD

**Issue by mykiimike** [jduncanator/node-diskusage#19]
Full information here https://travis-ci.org/binarysec/gate/jobs/233152067

Seems to be a problem with
```
cc1plus: error: unrecognized command line option ‘-std=c++11’
```

**Comment by jduncanator** [comment]
The warning message from node provides the answer:

> Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.

You'll need to update the compiler version on Travis to something that supports C++11.

You can install a supporting version of GCC with the following commands in the install section of the Travis config:

```
   sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
   sudo apt-get update -qq
   sudo apt-get install g++-4.9
```
