### ISSUE TITLE
SyntaxError: invalid syntax Node.JS 6.10.0

### ISSUE THREAD

**Issue by uribes78** [jduncanator/node-diskusage#23]
I have try to install the package and got this error

`> diskusage@0.2.3 install /opt/epbx/node_modules/diskusage
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 243, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-642.13.1.el6.i686
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/epbx/node_modules/diskusage
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN epbx@1.0.0 No repository field.
npm ERR! Linux 2.6.32-642.13.1.el6.i686
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "diskusage@0.2.3"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! diskusage@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the diskusage@0.2.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the diskusage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs diskusage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls diskusage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/epbx/npm-debug.log
`

I have been looking to see if there is a dependency not solved, but didn't find a clue. Can you help me to now what am I doing wrong? Thanks

**Comment by uribes78** [comment]
I've tried using an old node version (4.8.6) because I have a VM using that version and have not problem installing, but In the main server have the error.

**Comment by jduncanator** [comment]
I've tried reproducing on my end with Node 6.10.0 and npm 3.10.10, but haven't been able to reproduce the issue you are encountering.

Could you try deleting your entire node_modules folder and installing the package again? I suspect the gyp file has become corrupted somehow.

```
~/Build/node/diskusage# node -v
v6.10.0
~/Build/node/diskusage# npm -v
3.10.10
~/Build/node/diskusage# npm install diskusage

> diskusage@0.2.4 install /root/Build/node/diskusage/node_modules/diskusage
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/root/Build/node/diskusage/node_modules/diskusage/build'
  CXX(target) Release/obj.target/diskusage/src/main.o
  CXX(target) Release/obj.target/diskusage/src/diskusage_posix.o
  SOLINK_MODULE(target) Release/obj.target/diskusage.node
  COPY Release/diskusage.node
make: Leaving directory '/root/Build/node/diskusage/node_modules/diskusage/build'
/root/Build/node/diskusage
└─┬ diskusage@0.2.4
  └── nan@2.7.0

npm WARN enoent ENOENT: no such file or directory, open '/root/Build/node/diskusage/package.json'
npm WARN diskusage No description
npm WARN diskusage No repository field.
npm WARN diskusage No README data
npm WARN diskusage No license field.
```

**Comment by jduncanator** [comment]
@uribes78 Have you tried the above suggestion? Without further information, I can't investigate any further.

Closing this for now, if more information provided, I'll reopen.
