### ISSUE TITLE
Check is not async

### ISSUE THREAD

**Issue by CSester** [jduncanator/node-diskusage#24]
Hi,

I was wondering why this library exposes 2 fonctions (sync and async) since both are synchronous ?
Let's watch to the code (index.js):
```javascript
exports.check = function(path, callback) {
    var result = undefined;
    var error = undefined;
    try {
        result = native.getDiskUsage(path);
    }
    catch (error_) {
        error = error_
    }
    callback(error, result);
};
```
This executes the code synchronously, catch errors and call the given callback. But it is not asynchronous !

If you add some sleep() call to diskusage_posix.cpp :
```c
DiskUsage GetDiskUsage(const char* path)
{
    struct statvfs info = {};

    if (statvfs(path, &info)) {
        int errnum = errno;
        throw SystemError(errnum, "statvfs", strerror(errnum), path);
    }

    sleep(5); //<-- This is the addition
    DiskUsage result;
    result.available = info.f_bavail * info.f_frsize;
    result.free = info.f_bfree * info.f_frsize;
    result.total = info.f_blocks * info.f_frsize;

    return result;
}
```

The javascript execution will block until the return.

Are you interested by adding asynchronous support (and BTW promise also) to the library? If so, I would be pleased to submit a PR.

Best regards,

Cyril

**Comment by jduncanator** [comment]
Operating Systems don't expose any calls that would make this call asynchronous. The whole point of this library is that libuv doesn't provide an easy, asynchronous way to get free disk space. When they make that available, I'd imagine the changes would be merged into Node.js and there would be a native replacement for this library.

That being said, there are _some_ options to make this asynchronous (eg. threads, queuing things on the event loop), but these are difficult to get working reliably and without over complicating the library.

If you'd like to submit a PR making the call itself asynchronous, I'd be more than happy to take a look, but it would need to be solid and as minimally complicated as possible.

I actually plan on pushing in some unit tests this week for the library, I'll write back here once their in and you can make sure your PR passes these still.

**Comment by CSester** [comment]
Investigating around, I came to the same conclusion. There is no simple and reliable way to get these information.

Nevertheless, why does the library expose these 2 functions? This is misleading IMO.

**Comment by jduncanator** [comment]
It's designed to follow the same API design as all the internal `fs` functions, these provide both an inline synchronous call that returns the information from the function call, and an "asynchronous" function call that provides the data via a callback.

Even though the second one is not truly asynchronous in our case, the function signature is still useful for people who are used to having both available with the `fs` API.

**Comment by matthiasg** [comment]
In this case the callback should be called in a `setTimeout(callback,0,error,result)` way or similar though, to ensure the callback behaves similar to node.js functions where the callback is executed asynchronously

**Comment by jduncanator** [comment]
@matthiasg You make a good point. The callback should ideally be called by `setImmediate` rather than directly. If you agree, I'll push a change and a new version of the library.

**Comment by matthiasg** [comment]
Makes sense. It would be after the IO events queue then which also makes sense.
