### ISSUE TITLE
diskusage.node is not a valid Win32 when bugger in vscode

### ISSUE THREAD

**Issue by JackoPham** [jduncanator/node-diskusage#28]
I'm get a problem when debug my project had use diskusage package on the windown 10.

Error:
node_modules\diskusage\build\Release\diskusage.node is not a valid Win32 application.

please help me fix it. 
thank you so much.

**Comment by jduncanator** [comment]
This looks like a compiler issue. You need to have a build chain installed on your computer to use diskusage, so you'll need something like Visual Studio on Windows to use diskusage.

**Comment by jduncanator** [comment]
Closing unless more information can be provided.
