### ISSUE TITLE
Mac OS free/available disk space usage

### ISSUE THREAD

**Issue by marcoln** [jduncanator/node-diskusage#35]
Hi,

I believe diskusage takes wrong variables at MacOS, here is DiskUsage structure returned on my Mac:

{ available: 234734542848,
  free: 772926418944,
  total: 1000240963584 }

My disk is 1TB, ~770 GB used and ~230 free

**Comment by jduncanator** [comment]
Are you able to run the following command in a terminal and report the result back here?

```
df 
```

**Comment by marcoln** [comment]
hello, of course. This is result from Mac OS:

Filesystem    512-blocks      Used Available Capacity iused               ifree %iused  Mounted on
/dev/disk1s1  1953595632 455931488 432383256    52% 1466401 9223372036853309406    0%   /
devfs                396       396         0   100%     686                   0  100%   /dev
/dev/disk1s4  1953595632  16777296 432383256     4%       8 9223372036854775799    0%   /private/var/vm
map -hosts             0         0         0   100%       0                   0  100%   /net
map auto_home          0         0         0   100%       0                   0  100%   /home
/dev/disk1s5  1953595632 444000368 432383256    51%  100324 9223372036854675483    0%   /Volumes/MARKO
/dev/disk1s7  1953595632 246674960 432383256    37%     115 9223372036854775692    0%   /Volumes/VM
/dev/disk1s8  1953595632 332153184 432383256    44%   15730 9223372036854760077    0%   /Volumes/Archiwum
/dev/disk1s9  1953595632  22775072 432383256     6%    7724 9223372036854768083    0%   /Volumes/Downloads

df -h

Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   932Gi  217Gi  207Gi    52% 1466434 9223372036853309373    0%   /
devfs          198Ki  198Ki    0Bi   100%     686                   0  100%   /dev
/dev/disk1s4   932Gi  7.0Gi  207Gi     4%       7 9223372036854775800    0%   /private/var/vm
map -hosts       0Bi    0Bi    0Bi   100%       0                   0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0                   0  100%   /home
/dev/disk1s5   932Gi  212Gi  207Gi    51%  100324 9223372036854675483    0%   /Volumes/MARKO
/dev/disk1s7   932Gi  118Gi  207Gi    37%     115 9223372036854775692    0%   /Volumes/VM
/dev/disk1s8   932Gi  158Gi  207Gi    44%   15730 9223372036854760077    0%   /Volumes/Archiwum
/dev/disk1s9   932Gi   11Gi  207Gi     5%    7724 9223372036854768083    0%   /Volumes/Downloads

OK, I believe I know what is the issue here. I have single 1TB disk and it is divided into number of volumes. All of those volumes share common disk space. The size of the volume is flexible, it is not rigid as of regular partition. So all volumes report they are 1TB size, they report how much they use on the volume and as the free space they report 1TB minus sum of all volumes. Looks like it’s not a bug in disk space, but specific behaviour of Apple APFS containers





and this is result from target device I intend to run the software I’m working on:

Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  2.4G  910M  1.3G  42% /imgpart
/dev/loop0      270M  270M     0 100% /static
overlay         2.6G  516M  1.9G  22% /
devtmpfs        498M     0  498M   0% /dev
tmpfs           510M  4.1k  510M   1% /dev/shm
tmpfs           510M  4.9M  505M   1% /run
tmpfs           5.3M  4.1k  5.3M   1% /run/lock
tmpfs           510M     0  510M   0% /sys/fs/cgroup
tmpfs           510M   29k  510M   1% /tmp
tmpfs           510M     0  510M   0% /var/spool/cups
tmpfs            21M   46k   21M   1% /var/log
tmpfs           510M     0  510M   0% /var/spool/cups/tmp
/dev/mmcblk0p1   63M   49M   15M  78% /boot
/dev/sda2       180G  121G   59G  68% /media/Internal
/dev/sda1       207M   512  207M   1% /media/EFI
tmpfs           102M     0  102M   0% /run/user/1000

Cheers,
Marek

**Comment by tumdav** [comment]
same for ubuntu

**Comment by jduncanator** [comment]
@tumdav Can you provide the output of both diskusage and the `df` command under Ubuntu?

**Comment by SAtacker** [comment]
I am in a similar situation ( devices under `/dev/` ).
Can anybody help?

**Comment by SAtacker** [comment]
Ran demo code given
```sh
debian@beaglebone:~/node_pr$ node demo.js 
224317440
224317440
224317440
224317440
224317440
224317440
free: 224317440
debian@beaglebone:~/node_pr$ df /dev/mmcblk0p1 
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/mmcblk0p1  30623028 2106704  27221384   8% /
```
