### ISSUE TITLE
Fails to build on VS 2019

### ISSUE THREAD

**Issue by GDreyV** [jduncanator/node-diskusage#43]
Msbuild has different location on VS2019 it's "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" (not ...\MSBuild\v15\Bin\...)

**Comment by jduncanator** [comment]
I think this is a node-gyp problem, not a diskusage problem? May be best to report this to the node-gyp repository.

**Comment by jduncanator** [comment]
This has been resolved in node-gyp 5.0 (see relevant discussion [here](https://github.com/nodejs/node-gyp/pull/1762) and [here](https://github.com/nodejs/node-gyp/pull/1715)). Until node-gyp 5.0 lands with npm, you can follow instructions [here](https://github.com/nodejs/node-gyp/pull/1715#issuecomment-502211967) to manually install it.
