### ISSUE TITLE
diskusage@1.1.2 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by RF-Bernhard** [jduncanator/node-diskusage#48]
Hello! I tried to install diskusage 1.1.2 via npm and got following error:

![Bildschirmfoto vom 2019-11-16 15-05-37](https://user-images.githubusercontent.com/35370293/68994394-c6a9aa00-0882-11ea-8286-0ba70f0104db.png)

[npm-debug.log](https://github.com/jduncanator/node-diskusage/files/3854249/npm-debug.log)

Anyone got an idea of whats going on? Is it a bug or a bad configuration of my system? As you can see on the log I'm using:
Linux Mint 19.2 (Linux 4.15.0-66-generic)
Node 8.10.0
Npm 3.5.2

I also figured out that the pathname to my node-gyp does not contain empty spaces (a typical issue). Thanks for your help!

**Comment by jduncanator** [comment]
Looks like you need the build-essentials package installed on your machine, you’re missing a C++ compiler.
