### ISSUE TITLE
Incorrectly reports free/available disk space

### ISSUE THREAD

**Issue by garyking** [jduncanator/node-diskusage#51]
For some reason, this library has recently been reporting free/available disk space incorrectly.

It's reporting 22 GB free, but I've got 65 GB free.

**Comment by jduncanator** [comment]
Can you please provide more information?

At a minimum, provide the output of diskusage, and then either `df` or some other output that you're comparing it to.

**Comment by garyking** [comment]
`df` reports the same "wrong" available space. So I guess the problem isn't with this library.
