### ISSUE TITLE
Setting a threshold for usage limit.

### ISSUE THREAD

**Issue by chainhead** [jduncanator/node-diskusage#56]
I have a project where files are written to a mount point e.g. `/data`. I would like to apply a validation rule such that the process is exited if the percentage of space available at `/data` drops to say, 5%. For the purpose of testing, I used `/Users/myuserid` as the path for which the percentage maybe calculated. However, I am not following the results.

## Code
```js
const disku = require('diskusage');
const bytes = require('bytes')

let path = '/Users/myuserid'
disku.check(path, (err, info) => {
 if (err) { console.log(`${err}`) } 
 else {
    console.log(`Free: ${bytes(info.free)} Available: ${bytes(info.available)} Total: ${bytes(info.total)}`)}
})
```

## Results

```bash
Free: 21.82GB Available: 9.12GB Total: 112.8GB
```

Is the available space `9.12GB` out of a total limit of `21.82GB`? The `112.8GB` includes the space used by other users also. Therefore, I am not sure, if I were to calculate the percentage available for the current user, what should be my denominator - `9.12GB` or `112.8GB`?

**Comment by jduncanator** [comment]
Free disk space is the amount of physical free space left on the drive. Available disk space is the amount of free disk space available to the current user. Some spaces is usually reserved for the root user, so it is not available to standard users, which is reflected in the available figure.

If you want to determine the percentage of available space for the current user, you should use `available / total * 100`.

**Comment by chainhead** [comment]
1. Is it possible to find out the space _consumed_ by the current user? 
2. Is the `available` space the size that is _now_ remaining? If so, how can we find out how much was originally allocated to that user?

**Comment by jduncanator** [comment]
Neither of those are possible with this library. To do (1), you'd need to sum up all the sizes of files in a specific folder a user "owned". (2) doesn't really make sense, as the user is allocated all the space, minus the space reserved for the root user. You could probably compute this value by working out `total - (free - available)` which will give you the amount of space reserved for the root user.
