### ISSUE TITLE
diskusage does not work with Node JS 4.x

### ISSUE THREAD

**Issue by jschrab** [jduncanator/node-diskusage#7]
It would appear this is because of the https://github.com/node-ffi/node-ffi dependency:
https://github.com/node-ffi/node-ffi/issues/245

I mention this here in hopes that the node-diskusage repo is updated to use the next release of node-ffi, once it's ready.

**Comment by dimd13** [comment]
+

**Comment by jduncanator** [comment]
Thanks for letting me know. I'm rather busy this week so I will take a look at this as well as push an NPM update over the weekend.

**Comment by SirAnthony** [comment]
It is fine from git, please update npm package.

**Comment by hellboy81** [comment]
Can `node-diskusage`  version `0.1.3` work with node `0.12` ?

**Comment by jduncanator** [comment]
@hellboy81 When I get around to releasing an update it will work on 0.12. I'm working on a few changes to library before I release the next version

**Comment by hellboy81** [comment]
Hmm.. Which incompatibilities has the current version  `node-diskusage` with node 0.12?

**Comment by hellboy81** [comment]
As I mentioned the [`node-ffi` since version `1.3.0 / 2015-03-22` supports `0.12.x`](http://git.io/vCiyj):

> - add support for io.js >= v1.1.0 and node.js v0.12.x via na

**Comment by hellboy81** [comment]
We are still waiting for 0.12 compatible version...

**Comment by hellboy81** [comment]
This library can be replaced with [diskspace.js](https://github.com/keverw/diskspace.js)

**Comment by jduncanator** [comment]
Sorry for the huge delays. I've setup automatic deployment now so it shouldn't happen again in the future. Version 0.1.4 is now available on npm.

As the API changed in a non-breaking manner I decided not to bump to version 0.2.x and instead went to 0.1.4.

**Comment by starquake** [comment]
Thanks! It works! I prefer your use of statvfs and GetDiskFreeSpaceEx over parsing the output of a command line tool.
