### ISSUE TITLE
Consider changing license to MIT

### ISSUE THREAD

**Issue by mihail-stanchev** [jduncanator/node-diskusage#8]
Hi, would you consider changing the license to MIT? This would allow the module to be used in (potentially commercial) redistributed software, e.g. atom-based desktop applications, etc.

**Comment by jduncanator** [comment]
Sure. I have no qualms over changing the license so long as it doesn't affect anyone else who is currently using the library. If anyone objects to the change feel free to leave a comment!

**Comment by jduncanator** [comment]
I'll be swapping the license to MIT on the 1st of February unless anyone has an objection (and a decent reason).

**Comment by Magnitus-** [comment]
That would be fantastic. 

I'm considering using this module as a dependency for a customer support tool I've been contracted to develop. The only hurdle atm is the license.

**Comment by jduncanator** [comment]
I'll be moving the license to MIT tomorrow, if anyone has any last minute objections, speak now or forever hold your peace!

**Comment by jduncanator** [comment]
The project is now licensed under the MIT license which is compatible with the GPL license (afaik). If anyone has any issues, feel free to contact me.

**Comment by mihail-stanchev** [comment]
Thanks!
Maybe also update package.json and npm publish?

**Comment by jduncanator** [comment]
@mihail-stanchev Sure! I've had a few changes I wanted to make before hand, but I'll see if I find the time tonight to do it.

**Comment by jduncanator** [comment]
@mihail-stanchev Sorry it took so long, I've published 0.1.5 with the updated MIT License!

**Comment by mihail-stanchev** [comment]
@jduncanator Thanks, just about right timing ;)
